### ISSUE TITLE
Cannot find module internal/fs

### ISSUE THREAD

**Issue by kriskhaira** [netlify/netlify-cli#25]
I'm getting the following error when running any netlify command e.g. `netlify` or `netlify deploy`.

> Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/usr/local/lib/node_modules/netlify-cli/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:3
    at tryModuleLoad (module.js:447:12)

## My environment

- Node.js: v7.8.0
- NPM: 4.2.0
- Yarn: 0.17.8
- macOS: Sierra 10.12.4 (16E195)

**Comment by kriskhaira** [comment]
Turns out this wasn't related specifically to netlify-cli. I've posted a solution here.
https://github.com/nodejs/node/issues/9377#issuecomment-296179745
