### ISSUE TITLE
`update-notifier` not found

### ISSUE THREAD

**Issue by rarkins** [netlify/netlify-cli#4]
Attempting to use `netlify-cli` for the first time:

```
$ sudo npm install -g netlify-cli
/usr/local/bin/netlify -> /usr/local/lib/node_modules/netlify-cli/bin/cli.js
netlify-cli@0.3.3 /usr/local/lib/node_modules/netlify-cli
├── home-dir@0.2.0
├── open@0.0.5
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── github@0.2.4 (mime@1.3.4)
├── inquirer@0.11.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, figures@1.4.0, ansi-escapes@1.1.0, cli-width@1.1.0, through@2.3.8, chalk@1.1.1, rx-lite@3.1.2, cli-cursor@1.0.2, readline2@1.0.1, run-async@0.1.0, lodash@3.10.1)
├── netlify@0.3.3 (base64-js@0.0.8, graceful-fs@3.0.8, glob@6.0.1)
└── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.8.3, utile@0.2.1)
$ netlify deploy
module.js:338
    throw err;
          ^
Error: Cannot find module 'update-notifier'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/netlify-cli/bin/cli.js:16:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Rhyss-iMac:web rhys$ sudo npm install -g update-notifier
update-notifier@0.6.0 /usr/local/lib/node_modules/update-notifier
├── is-npm@1.0.0
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── repeating@2.0.0 (is-finite@1.0.1)
├── semver-diff@2.1.0 (semver@5.1.0)
├── configstore@1.4.0 (os-tmpdir@1.0.1, object-assign@4.0.1, graceful-fs@4.1.2, uuid@2.0.1, xdg-basedir@2.0.0, osenv@0.1.3, write-file-atomic@1.1.4, mkdirp@0.5.1)
└── latest-version@2.0.0 (package-json@2.3.0)
$ netlify deploy
Opening https://app.netlify.com/authorize?
```

i.e. it worked only after I manually installed `update-notifier` globally.

```
$ node --version
v0.12.7
$ npm --version
2.11.3
```

**Comment by axecopfire** [comment]
I just ran `npm i -g netlify-cli` to update from version `3.34.0` to `3.35.0`.  All `netlify` commands now return:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'update-notifier'
Require stack:
- /home/[user]/.nvm/versions/node/v14.15.3/lib/node_modules/netlify-cli/src/index.js
- /home/[user]/.nvm/versions/node/v14.15.3/lib/node_modules/netlify-cli/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/[user]/.nvm/versions/node/v14.15.3/lib/node_modules/netlify-cli/src/index.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/[user]/.nvm/versions/node/v14.15.3/lib/node_modules/netlify-cli/src/index.js',
    '/home/[user]/.nvm/versions/node/v14.15.3/lib/node_modules/netlify-cli/bin/run'
  ]
}
```

**Comment by erezrokah** [comment]
Hi @axecopfire, do you mind updating `npm` to the latest version, then trying again?
You can do it by running `npm install -g npm@latest`, then running `npm install -g netlify-cli@latest`.

If that doesn't work, can you try `npm uninstall -g netlify-cli`, then `npm install -g netlify-cli`?

**Comment by axecopfire** [comment]
Ahh thank you. I've been troubleshooting a different issue and didn't realize I was still on an older version.
